const_value = 1

	const DEX_BULBASAUR  ; 1
	const DEX_IVYSAUR    ; 2
	const DEX_VENUSAUR   ; 3
	const DEX_CHARMANDER ; 4
	const DEX_CHARMELEON ; 5
	const DEX_CHARIZARD  ; 6
	const DEX_SQUIRTLE   ; 7
	const DEX_WARTORTLE  ; 8
	const DEX_BLASTOISE  ; 9
	const DEX_CATERPIE   ; 10
	const DEX_METAPOD    ; 11
	const DEX_BUTTERFREE ; 12
	const DEX_WEEDLE     ; 13
	const DEX_KAKUNA     ; 14
	const DEX_BEEDRILL   ; 15
	const DEX_PIDGEY     ; 16
	const DEX_PIDGEOTTO  ; 17
	const DEX_PIDGEOT    ; 18
	const DEX_RATTATA    ; 19
	const DEX_RATICATE   ; 20
	const DEX_SPEAROW    ; 21
	const DEX_FEAROW     ; 22
	const DEX_EKANS      ; 23
	const DEX_ARBOK      ; 24
	const DEX_PIKACHU    ; 25
	const DEX_RAICHU     ; 26
	const DEX_PIKABLU    ; 27
	const DEX_RAIBLU     ; 28
	const DEX_SANDSHREW  ; 29
	const DEX_SANDSLASH  ; 30
	const DEX_NIDORAN_F  ; 31
	const DEX_NIDORINA   ; 32
	const DEX_NIDOQUEEN  ; 33
	const DEX_NIDORAN_M  ; 34
	const DEX_NIDORINO   ; 35
	const DEX_NIDOKING   ; 36
	const DEX_CLEFAIRY   ; 37
	const DEX_CLEFABLE   ; 38
	const DEX_VULPIX     ; 39
	const DEX_NINETALES  ; 40
	const DEX_JIGGLYPUFF ; 41
	const DEX_WIGGLYTUFF ; 42
	const DEX_ZUBAT      ; 43
	const DEX_GOLBAT     ; 44
	const DEX_ODDISH     ; 45
	const DEX_GLOOM      ; 46
	const DEX_VILEPLUME  ; 47
	const DEX_BELLOSSOM  ; 48
	const DEX_PARAS      ; 49
	const DEX_PARASECT   ; 50
	const DEX_VENONAT    ; 51
	const DEX_VENOMOTH   ; 52
	const DEX_DIGLETT    ; 53
	const DEX_DUGTRIO    ; 54
	const DEX_MEOWTH     ; 55
	const DEX_PERSIAN    ; 56
	const DEX_PSYDUCK    ; 57
	const DEX_GOLDUCK    ; 58
	const DEX_MANKEY     ; 59
	const DEX_PRIMEAPE   ; 60
	const DEX_GROWLITHE  ; 61
	const DEX_ARCANINE   ; 62
	const DEX_POLIWAG    ; 63
	const DEX_POLIWHIRL  ; 64
	const DEX_POLIWRATH  ; 65
	const DEX_ABRA       ; 66
	const DEX_KADABRA    ; 67
	const DEX_ALAKAZAM   ; 68
	const DEX_MACHOP     ; 69
	const DEX_MACHOKE    ; 70
	const DEX_MACHAMP    ; 71
	const DEX_BELLSPROUT ; 72
	const DEX_WEEPINBELL ; 73
	const DEX_VICTREEBEL ; 74
	const DEX_TENTACOOL  ; 75
	const DEX_TENTACRUEL ; 76
	const DEX_GEODUDE    ; 77
	const DEX_GRAVELER   ; 78
	const DEX_GOLEM      ; 79
	const DEX_PONYTA     ; 80
	const DEX_RAPIDASH   ; 81
	const DEX_SLOWPOKE   ; 82
	const DEX_SLOWBRO    ; 83
	const DEX_MAGNEMITE  ; 84
	const DEX_MAGNETON   ; 85
	const DEX_FARFETCHD  ; 86
	const DEX_DODUO      ; 87
	const DEX_DODRIO     ; 88
	const DEX_SEEL       ; 89
	const DEX_DEWGONG    ; 90
	const DEX_GRIMER     ; 91
	const DEX_MUK        ; 92
	const DEX_SHELLDER   ; 93
	const DEX_CLOYSTER   ; 94
	const DEX_GASTLY     ; 95
	const DEX_HAUNTER    ; 96
	const DEX_GENGAR     ; 97
	const DEX_ONIX       ; 98
	const DEX_DROWZEE    ; 99
	const DEX_HYPNO      ; 100
	const DEX_KRABBY     ; 101
	const DEX_KINGLER    ; 102
	const DEX_VOLTORB    ; 103
	const DEX_ELECTRODE  ; 104
	const DEX_EXEGGCUTE  ; 105
	const DEX_EXEGGUTOR  ; 106
	const DEX_CUBONE     ; 107
	const DEX_MAROWAK    ; 108
	const DEX_HITMONLEE  ; 109
	const DEX_HITMONCHAN ; 110
	const DEX_LICKITUNG  ; 111
	const DEX_KOFFING    ; 112
	const DEX_WEEZING    ; 113
	const DEX_RHYHORN    ; 114
	const DEX_RHYDON     ; 115
	const DEX_CHANSEY    ; 116
	const DEX_TANGELA    ; 117
	const DEX_KANGASKHAN ; 118
	const DEX_HORSEA     ; 119
	const DEX_SEADRA     ; 120
	const DEX_GOLDEEN    ; 121
	const DEX_SEAKING    ; 122
	const DEX_STARYU     ; 123
	const DEX_STARMIE    ; 124
	const DEX_MR_MIME    ; 125
	const DEX_SCYTHER    ; 126
	const DEX_JYNX       ; 127
	const DEX_ELECTABUZZ ; 128
	const DEX_MAGMAR     ; 129
	const DEX_PINSIR     ; 130
	const DEX_TAUROS     ; 131
	const DEX_MAGIKARP   ; 132
	const DEX_GYARADOS   ; 133
	const DEX_LAPRAS     ; 134
	const DEX_DITTO      ; 135
	const DEX_EEVEE      ; 136
	const DEX_VAPOREON   ; 137
	const DEX_JOLTEON    ; 138
	const DEX_FLAREON    ; 139
	const DEX_PORYGON    ; 140
	const DEX_OMANYTE    ; 141
	const DEX_OMASTAR    ; 142
	const DEX_KABUTO     ; 143
	const DEX_KABUTOPS   ; 144
	const DEX_AERODACTYL ; 145
	const DEX_SNORLAX    ; 146
	const DEX_ARTICUNO   ; 147
	const DEX_ZAPDOS     ; 148
	const DEX_MOLTRES    ; 149
	const DEX_DRATINI    ; 150
	const DEX_DRAGONAIR  ; 151
	const DEX_DRAGONITE  ; 152
	const DEX_MEWTWO     ; 153
	const DEX_MEW        ; 154

NUM_POKEMON    EQU 154
